### PR TITLE
[WIP] Feature/flag campaign as invalid when no budget left

### PR DESCRIPTION
**Pull request by GustavoRSSilva**

### CODE REVIEW

**Comment by GustavoRSSilva** [comment]
@DioPires @tcrosado @zepcp,

We should make an effort to implement a style guide for the project, we should all follow the same style guide (some use snake case, others camel case).

I think [solhint](https://protofire.github.io/solhint/) is the best and the more used linter.

The solidity oficial style guide. http://solidity.readthedocs.io/en/v0.4.21/style-guide.html

**Comment by tcrosado** [comment]
I already did some research on solidity style guide, the first tool I saw was Solium. https://www.getsolium.com/
I guess it does a bit more than a classic linter.

**Comment by DioPires** [comment]
I agree that we should use the same convention regarding the style guide for the Solidity code. I had already seen [solhint](https://protofire.github.io/solhint/) and I think it's a good option

**Pull request merged**
