### PR TITLE
Linter

### PR DESCRIPTION
**Pull request by tcrosado**
- Added Solium linter for pre-commit
- Allows warnings but commit fails when errors are found by the linter
- Moved deploy content to root directory
- Need to rerun ` npm install`

### CODE REVIEW

**Comment by DioPires** [comment]
@tcrosado should we have a pre-commit hook to run the linter script?

**Review by GustavoRSSilva — APPROVED** [review]

**Comment by tcrosado** [comment]
@DioPires `npm install` should install the pre-commit package and solium
after that, every commit should have the pre-commit script working out of the box

**Review by DioPires — APPROVED** [review]
Everything seems to be in order

**Pull request merged**
