### PR TITLE
Get campaigns

### PR DESCRIPTION
**Pull request by tcrosado**

### CODE REVIEW

**Comment by DioPires** [comment]
@tcrosado so the pattern to get all campaigns would be to call **getTotalCampaignsByCountry** with a country ISO code (PT, US, etc), and then iterate over the number of campaigns in that country and call all the getter methods (one for each campaign attribute). Is this correct?

How would one know which countries have campaigns in the first place? Should we have a list of countries for which campaigns exist, that would be updated every time a new campaign is added/deleted (I know we're not yet addressing the _deleting campaigns_ part)? Then one would first get the countries and then perform the pattern above. What do you think?

**Comment by tcrosado** [comment]
Correct, it is necessary to first get the total campaigns of a certain country and later iterate over each campaign.
It is possible to have a list of countries to keep track of the mapping keys but as the most frequent use case is a user getting a list of campaigns based on his location I though there is no need to keep track of the existing locations. In case of campaign changes wouldn't it be better to keep a owner => Campaign mapping?

**Comment by DioPires** [comment]
For me it isn't clear that the most common use case is a user getting a list of campaigns based on his location. Since presenting campaigns is a responsibility of the app stores, they might want to get all the campaigns a few times a day or even once a day and then filter them as they need to show to users that match the campaigns' filters (location, package, vercode). If this is the case, then we should provide an easy way for them to get all campaigns at once.

> In case of campaign changes wouldn't it be better to keep a owner => Campaign mapping?

Could you explain what's the use pattern this would help with?

**Pull request merged**
